### PR TITLE
allow docker.io images on systems behind proxy

### PR DESCRIPTION
**Pull request by niravnshah**
To allow knative to pull docker.io images when run from behind the proxy while executing the deployer

## Summary

A small summary of the requirements (in one/two sentences).

## Implementation Notes :hammer_and_pick:

* Briefly outline the overall technical solution. If necessary, identify talking points where the reviewer's attention should be drawn to.

## External Dependencies :four_leaf_clover:

* 

## Breaking API Changes :warning:

* 

*Simply specify none (N/A) if not applicable.*

### CODE REVIEW

**Comment by ustiugov** [comment]
@niravnshah Thank you for the contribution! shall we merge it? if so, please rebase and mark ready

**Comment by ustiugov** [comment]
@niravnshah could you please help us finalize your contribution?

**Comment by niravnshah** [comment]
Hi @ustiugov , The change is final only and working on my system which is behind proxy. However, I am not sure why is it failing the unit tests in the workflow,. If you happen to understand the cause of the failure, it would be great to solve.

**Comment by ustiugov** [comment]
@niravnshah Please ignore the errors. Could you please rebase the change on the tip of the main branch? 

```
git checkout branch_name
git rebase -i origin/main
Git push branch_name
```

**Comment by niravnshah** [comment]
@ustiugov , I have rebased the branch to the HEAD of main.

**Comment by ustiugov** [comment]
@niravnshah thanks! please sign your commit with:
```
git commit -s --amend
git push -f

**Comment by niravnshah** [comment]
> @niravnshah thanks! please sign your commit with:
> 
> ```
> git commit -s --amend
> git push -f
> ```

Signed. Sorry for missing out earlier. Not used to sign commits.

**Comment by ustiugov** [comment]
@niravnshah we have the CRI tests broken in the CI #557. If you could confirm that the code in this branch works for you on bare metal, we can merge this PR right away.

**Comment by niravnshah** [comment]
Hi @ustiugov, yes, for me the change is working. However, I have done very limited testing and tried only couple of example functions (hello world, pyaes and rnn-serving). I hope this doent create any other issue for anyone else. If so, feel free to revert this change.

**Comment by ustiugov** [comment]
Thank you for the contribution!

**Pull request merged**
