### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by boramalper**
includes #289, #317, #328, #329, #330, #332

Signed-off-by: Bora M. Alper <bora@boramalper.org>

### CODE REVIEW

**Comment by boramalper** [comment]
I could not execute #319...

```
$ pwd
/home/.../ease/vhive/utils/benchmarking/eventing

$ go get google.golang.org/protobuf@v1.27.1
google.golang.org/protobuf: no Go source files
package google.golang.org/protobuf: build constraints exclude all Go files in /home/bora/go/pkg/mod/google.golang.org/protobuf@v1.27.1
```

No idea what might be the cause.

**Review by ustiugov — APPROVED** [review]

**Comment by ustiugov** [comment]
Ok let's skip the protobuf, please close those PRs

**Comment by boramalper** [comment]
Closed all except #319

**Comment by ustiugov** [comment]
@amohoste there is some weird [error](https://github.com/ease-lab/vhive/pull/333/checks?check_run_id=3016577250#step:8:470) happening with the local registry. This PR only updates a bunch of quite innocuous dependencies...

Could you please take a look?

**Comment by ustiugov** [comment]
@amohoste I think the problem was in our self-hosted runner getting corrupted. seems that that error is gone now

**Pull request merged**
