### PR TITLE
[hotfix] Remove skopeo dependency

### PR DESCRIPTION
**Pull request by ustiugov**
Related to the issue #402 

Signed-off-by: Dmitrii Ustiugov <dmitrii.ustiugov@ed.ac.uk>

### CODE REVIEW

**Review by cvetkovic — CHANGES_REQUESTED** [review]
The changes in `scripts/setup_system.sh` are a sufficient hotfix for this issue. 

`cri/Makefile` can therefore be discarded.

**Comment by ustiugov** [comment]
> The changes in `scripts/setup_system.sh` are a sufficient hotfix for this issue. 
> 
> 
> 
> `cri/Makefile` can therefore be discarded.

Without these changes, the CRI tests would be broken

**Comment by cvetkovic** [comment]
Then proceed with the merge.

**Comment by ustiugov** [comment]
thanks @cvetkovic it's best if you approved using the button though

**Review by cvetkovic — APPROVED** [review]
Changes approved!

**Pull request merged**
