### PR TITLE
Hotfix: Set scripts/disable_auto_updates.sh executable bit

### PR DESCRIPTION
**Pull request by boramalper**
`setup_node.sh` fails to execute `disable_auto_updates.sh` because of the missing executable bit on the file.

Signed-off-by: Bora M. Alper <bora@boramalper.org>

### CODE REVIEW

**Comment by ustiugov** [comment]
please rebase

**Comment by boramalper** [comment]
> please rebase

It already is?

**Comment by ustiugov** [comment]
now it is. can you, however, move this script to a new folder `scripts/utils` because `scripts/` is becoming a mix of everything? (needs refactoring at some point later)

**Review by ustiugov — DISMISSED** [review]

**Comment by ustiugov** [comment]
please rebase it again, we had to give an external PR a priority

**Comment by boramalper** [comment]
@ustiugov Done.

**Review by ustiugov — APPROVED** [review]

**Pull request merged**
